[package]
name = "byte-match"
version = "0.1.0"
authors = ["hk <alexhaka10@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dev-dependencies]
expand = "0.1.3"
